SELECT
'db_check_db_disk_group' as "db_check_db_disk_group",
NAME,
STATE,
TYPE,
(CASE WHEN STATE = 'DISMOUNTED' THEN 1 WHEN STATE = 'BROKEN' THEN 2 ELSE 0 END) STATE_NUM ,
round(TOTAL_MB/1024) TOTAL_GB,
round(FREE_MB/1024) FREE_GB,
round((TOTAL_MB-FREE_MB)/1024) USED_GB,
round((TOTAL_MB-FREE_MB)/TOTAL_MB*100) USED_PCT,
OFFLINE_DISKS
FROM V$ASM_DISKGROUP;
