/*数据库事务*/
SELECT
'db_check_db_transaction' as "db_check_db_transaction",
PROCPID as SESSION_ID,
START as START  ,
NOW() - START AS TRX_SECONDS,
round(date_part('epoch', NOW() - START)::NUMERIC / 60) AS VALUE,
CURRENT_QUERY as CURRENT_QUERY
FROM
(SELECT
BACKENDID,
PG_STAT_GET_BACKEND_PID(S.BACKENDID) AS PROCPID,
PG_STAT_GET_BACKEND_ACTIVITY_START(S.BACKENDID) AS START,
PG_STAT_GET_BACKEND_ACTIVITY(S.BACKENDID) AS CURRENT_QUERY
FROM
(SELECT PG_STAT_GET_BACKEND_IDSET() AS BACKENDID) AS S
) AS S
WHERE
CURRENT_QUERY <> '<IDLE>'
ORDER BY
trx_seconds DESC;